### ISSUE TITLE
Select2::multiSelect based upon ajax

### ISSUE THREAD

**Issue by harshitj2005** [buttflattery/yiiSelect2#1]
hi,

i have used this Select2::multiSelect to select muliple data but now i need to render data on ajax call as my data is getting bigger so it slows down the rendering of list. 
i have used this piece of code here but it says html specialhars expect parameter one to be strin but array given.

please have a look
echo Select2::multiSelect("outlets", $selectedOutlets, $emptyArray, array(
                        'placeholder' => 'Select outlets',
                        'style' => 'width:205px',
                        'select2Options'=>array(
                            'allowClear'=>true,
                            'placeholder'=>'Type outlets name Here',
                            'minimumInputLength'=>'3',
                            'ajax'=>array(
                                'url'=>Yii::app()->createUrl('userWinning/getoutletname'),
                                'type'=>'POST',
                                'dataType'=>'jsonp',
                                'data'=>new CJavaScriptExpression('function (term, page) {return {pattern: term, page:page}}'),
                                'results'=>new CJavaScriptExpression('function (data, page) {return {results:  data.locations}}'),
                            )
                        ),
                    ));

**Comment by buttflattery** [comment]
Sorry i was busy the whole time didnt logged in here , sorry for the late reply . Your first mistake seems to be that you are passing the array of values that you want to be shown selected when the page renders you are sending them in the value parameter this is where you are getting wrong you must use initSelection parameter to show already selected or tagged values in the multiselect i can paste here an example which is related to single select but that will fulfill what i am trying to tell , below is an example of browsing locations by selected city and you can see the example for initSelection to show the preselected values
add a table for cities and locations and see it working 

```
     <?php echo Select2::activeDropDownList($searchModel, 'city', CHtml::listData(Cities::model()->findAll(array('order' => 'name')), 'id', 'name'),
                array('empty' => '', 'id' => 'city', 'style' => 'width:100%',
                    'select2Options' => array(
                        'allowClear' => true,
                        'placeholder' => 'Type city to search',
                        'escapeMarkup' => new CJavaScriptExpression('function(m){return m;}'),
                    )
                )
            );
            ?>
            <?php
            //                                                echo Select2::dropDownList('location', '', CHtml::listData($locations, 'id', 'name'),
            //                                                array('empty'=>'','id'=>'location','style'=>'width:100%','select2Options'=>array('allowClear'=>true,'placeholder'=>'Type Location Here')));
            echo Select2::activeDropDownList($searchModel, 'location', array(),
                array(
                    'empty' => '',
                    'id' => 'location',
                    'style' => 'width:100%',
                    'select2Options' => array(
                        'allowClear' => true,
                        'placeholder' => 'Type Location Here',
                        'minimumInputLength' => '3',

                        'ajax' => array(
                            'url' => '/homes/locationsajax',
                            'type' => 'GET',
                            'dataType' => 'jsonp',
                            'data' => new CJavaScriptExpression('function (term, page, city_id) {return {loc_name: term, page:page, city_id:$("#city").select2("val")}}'),
                            'results' => new CJavaScriptExpression('function (data, page) {return {results:  data.locations}}'),

                        ),
                        'initSelection' => new CJavaScriptExpression('function(element, callback) { '
                            . 'var id=jQuery(element).val(); '
                            . 'if (id!=="") {'
                            . ' jQuery.ajax("/homes/locationsajax/loc_id/"+id+"/city_id/"+$("#city").select2("val"), { dataType: "jsonp" } ).done( function(data) {'
                            . ' callback(data)'
                            . '});'
                            . '}}'),
                        'escapeMarkup' => new CJavaScriptExpression('function (m) {return m;}'),
                    )
                )
            );
            ?>
```
